const mockGridData = [
    {
        analyticsServices: ['ChangeType.ADOBE_ANALYTICS', 'ChangeType.GOOGLE_ANALYTICS'],
        canonicalType: 'internal_self',
        canonicalUrl: 'https://www.conductor.com/',
        domain: 'www.conductor.com',
        https: true,
        indexable: true,
        inXMLSitemap: undefined,
        isDisallowedInRobotsTxt: false,
        isIndexableDueToMetaRobots: 'yes',
        isIndexableDueToXRobotsTag: 'yes',
        lighthousePerformance: { value: 82, range: 'WebVitalRange.Good' },
        lighthouseFCP: { value: 1700, range: 'WebVitalRange.Good' },
        lighthouseTTI: { value: 9200, range: 'WebVitalRange.Bad' },
        lighthouseSI: { value: 1500, range: 'WebVitalRange.Good' },
        lighthouseTBT: { value: 439, range: 'WebVitalRange.Bad' },
        lighthouseLCP: { value: 1900, range: 'WebVitalRange.Good' },
        lighthouseCLS: { value: 0, range: 'WebVitalRange.Good' },
        redirectTarget: 'https://www.conductor.com/',
        openGraphDescription: 'Explore culinary wonders with Conductor - recipes, blogs, and more!',
        openGraphImage: 'https://www.conductor.com/images/home.jpg',
        openGraphTitle: 'Conductor - Home',
        openGraphType: 'website',
        openGraphUrl: 'https://www.conductor.com/',
        schemaItems: 2,
        schemaTypes: 'Person, WebSite',
        statusCode: 200,
        tagManagers: ['ChangeType.GOOGLE_TAG_MANAGER'],
        twitterCard: 'summary_large_image',
        twitterDescription: 'Explore culinary wonders with Conductor - recipes, blogs, and more!',
        twitterImage: 'https://www.conductor.com/images/home.jpg',
        twitterSite: '@conductor',
        twitterTitle: 'Conductor - Home',
        url: 'https://www.conductor.com/',
        urlDepth: 12,
        urlFull: undefined,
        urlType: 'PageType.Page',
        visualAnalyticsServices: ['ChangeType.CLICKY', 'ChangeType.CRAZY_EGG', 'ChangeType.HOTJAR'],
    },
    {
        analyticsServices: null,
        canonicalType: 'cross_domain',
        canonicalUrl: 'https://www.conductor.com/recipes',
        domain: 'www.conductor.com',
        https: false,
        indexable: true,
        inXMLSitemap: true,
        isDisallowedInRobotsTxt: false,
        isIndexableDueToMetaRobots: 'no',
        isIndexableDueToXRobotsTag: 'yes',
        lighthousePerformance: { value: 62, range: 'WebVitalRange.NeedsImprovement' },
        lighthouseFCP: { value: 1600, range: 'WebVitalRange.Good' },
        lighthouseTTI: { value: 3200, range: 'WebVitalRange.Good' },
        lighthouseSI: { value: 2600, range: 'WebVitalRange.Good' },
        lighthouseTBT: { value: 494, range: 'WebVitalRange.Bad' },
        lighthouseLCP: { value: 2000, range: 'WebVitalRange.Good' },
        lighthouseCLS: { value: 10, range: 'WebVitalRange.NeedsImprovement' },
        redirectTarget: 'https://www.conductor.com/recipes',
        openGraphDescription: 'Discover a world of flavor - Conductor\'s diverse recipe collection awaits!',
        openGraphImage: 'https://www.conductor.com/images/recipes.jpg',
        openGraphTitle: 'Conductor - Recipes',
        openGraphType: 'website',
        openGraphUrl: 'https://www.conductor.com/recipes',
        schemaItems: 1,
        schemaTypes: 'WebSite',
        statusCode: 301,
        tagManagers: null,
        twitterCard: 'summary_large_image',
        twitterDescription: 'Discover a world of flavor - Conductor\'s diverse recipe collection awaits!',
        twitterImage: 'https://www.conductor.com/images/recipes.jpg',
        twitterSite: '@conductor',
        twitterTitle: 'Conductor - Recipes',
        url: 'https://www.conductor.com/recipes',
        urlDepth: 1,
        urlFull: undefined,
        urlType: 'PageType.Redirect',
        visualAnalyticsServices: null,
    },
    {
        analyticsServices: null,
        canonicalType: undefined,
        canonicalUrl: undefined,
        domain: 'www.conductor.com',
        https: null,
        indexable: true,
        inXMLSitemap: false,
        isDisallowedInRobotsTxt: true,
        isIndexableDueToMetaRobots: 'no',
        isIndexableDueToXRobotsTag: 'no',
        lighthousePerformance: { value: 67, range: 'WebVitalRange.NeedsImprovement' },
        lighthouseFCP: { value: 1000, range: 'WebVitalRange.Good' },
        lighthouseTTI: { value: 2200, range: 'WebVitalRange.Good' },
        lighthouseSI: { value: 3200, range: 'WebVitalRange.Good' },
        lighthouseTBT: { value: 308, range: 'WebVitalRange.NeedsImprovement' },
        lighthouseLCP: { value: 2200, range: 'WebVitalRange.Good' },
        lighthouseCLS: { value: 3, range: 'WebVitalRange.Good' },
        redirectTarget: 'https://www.conductor.com/recipes/vegan-salmon',
        openGraphDescription: undefined,
        openGraphImage: undefined,
        openGraphTitle: undefined,
        openGraphType: undefined,
        openGraphUrl: undefined,
        schemaItems: 0,
        schemaTypes: null,
        statusCode: 0,
        tagManagers: null,
        twitterCard: undefined,
        twitterDescription: undefined,
        twitterImage: undefined,
        twitterSite: undefined,
        twitterTitle: undefined,
        url: 'https://www.conductor.com/recipes/vegan-salmon',
        urlDepth: 3,
        urlFull: undefined,
        urlType: 'PageType.Missing',
        visualAnalyticsServices: null,
    },
    {
        analyticsServices: ['ChangeType.GOOGLE_ANALYTICS'],
        canonicalType: null,
        canonicalUrl: 'https://www.conductor.com/blog',
        domain: 'www.conductor.com',
        https: false,
        indexable: undefined,
        inXMLSitemap: false,
        isDisallowedInRobotsTxt: undefined,
        isIndexableDueToMetaRobots: 'yes',
        isIndexableDueToXRobotsTag: 'yes',
        lighthousePerformance: { value: 72, range: 'WebVitalRange.NeedsImprovement' },
        lighthouseFCP: { value: 1000, range: 'WebVitalRange.Good' },
        lighthouseTTI: { value: 8900, range: 'WebVitalRange.Bad' },
        lighthouseSI: { value: 4000, range: 'WebVitalRange.Good' },
        lighthouseTBT: { value: 210, range: 'WebVitalRange.NeedsImprovement' },
        lighthouseLCP: { value: 2100, range: 'WebVitalRange.Good' },
        lighthouseCLS: { value: 0, range: 'WebVitalRange.Good' },
        redirectTarget: 'https://www.conductor.com/',
        openGraphDescription: 'Get culinary insights and recipe recommendations from Conductor\'s blog.',
        openGraphImage: 'https://www.conductor.com/images/blog.jpg',
        openGraphTitle: 'Conductor - Blog',
        openGraphType: 'website',
        openGraphUrl: 'https://www.conductor.com/blog',
        schemaItems: 4,
        schemaTypes: 'Organization, Event, Review, WebSite',
        statusCode: 200,
        tagManagers: ['ChangeType.GOOGLE_TAG_MANAGER', 'ChangeType.SEGMENT_COM_TAG_MANAGER', 'fake_tag_manager'],
        twitterCard: 'summary_large_image',
        twitterDescription: 'Get culinary insights and recipe recommendations from Conductor\'s blog.',
        twitterImage: 'https://www.conductor.com/images/blog.jpg',
        twitterSite: '@conductor',
        twitterTitle: 'Conductor - Blog',
        url: 'https://www.conductor.com/blog',
        urlDepth: 7,
        urlFull: 'https://www.conductor.com/blog',
        urlType: 'PageType.Page',
        visualAnalyticsServices: ['ChangeType.SMARTLOOK'],
    },
    {
        analyticsServices: null,
        canonicalType: null,
        canonicalUrl: null,
        domain: null,
        https: null,
        indexable: null,
        inXMLSitemap: null,
        isDisallowedInRobotsTxt: null,
        isIndexableDueToMetaRobots: null,
        isIndexableDueToXRobotsTag: null,
        lighthousePerformance: null,
        lighthouseFCP: null,
        lighthouseTTI: null,
        lighthouseSI: null,
        lighthouseTBT: null,
        lighthouseLCP: null,
        lighthouseCLS: null,
        redirectTarget: null,
        openGraphDescription: null,
        openGraphImage: null,
        openGraphTitle: null,
        openGraphType: null,
        openGraphUrl: null,
        schemaItems: null,
        schemaTypes: null,
        statusCode: null,
        tagManagers: null,
        twitterCard: null,
        twitterDescription: null,
        twitterImage: null,
        twitterSite: null,
        twitterTitle: null,
        url: 'https://www.conductor.com/special/null',
        urlDepth: undefined,
        urlFull: 'https://www.conductor.com/special/null',
        urlType: null,
        visualAnalyticsServices: null,
    },
    {
        analyticsServices: ['ChangeType.ADOBE_ANALYTICS', 'fake_analytics_service'],
        canonicalType: 'internal_self',
        canonicalUrl: 'https://www.conductor.com/about',
        domain: 'www.conductor.com',
        https: true,
        indexable: true,
        inXMLSitemap: true,
        isDisallowedInRobotsTxt: true,
        isIndexableDueToMetaRobots: 'no',
        isIndexableDueToXRobotsTag: 'yes',
        lighthousePerformance: { value: 62, range: 'WebVitalRange.NeedsImprovement' },
        lighthouseFCP: { value: 1400, range: 'WebVitalRange.Good' },
        lighthouseTTI: { value: 6900, range: 'WebVitalRange.NeedsImprovement' },
        lighthouseSI: { value: 2400, range: 'WebVitalRange.Good' },
        lighthouseTBT: { value: 299, range: 'WebVitalRange.NeedsImprovement' },
        lighthouseLCP: { value: 1800, range: 'WebVitalRange.Good' },
        lighthouseCLS: { value: 24, range: 'WebVitalRange.Bad' },
        redirectTarget: 'https://www.conductor.com/about',
        openGraphDescription: 'Learn about Conductor\'s mission and the team behind the culinary magic.',
        openGraphImage: 'https://www.conductor.com/images/about.jpg',
        openGraphTitle: 'Conductor - About',
        openGraphType: 'website',
        openGraphUrl: 'https://www.conductor.com/about',
        schemaItems: 4,
        schemaTypes: 'BreadcrumbList, Person, Article, Event',
        statusCode: 307,
        tagManagers: ['ChangeType.ADOBE_TAG_MANAGER'],
        twitterCard: 'summary_large_image',
        twitterDescription: 'Learn about Conductor\'s mission and the team behind the culinary magic.',
        twitterImage: 'https://www.conductor.com/images/about.jpg',
        twitterSite: '@conductor',
        twitterTitle: 'Conductor - About',
        url: null,
        urlDepth: 1,
        urlFull: null,
        urlType: 'PageType.Page',
        visualAnalyticsServices: ['ChangeType.MOUSEFLOW', 'ChangeType.SMARTLOOK'],
    },
    {
        analyticsServices: '',
        canonicalType: '',
        canonicalUrl: '',
        domain: '',
        https: '',
        indexable: '',
        inXMLSitemap: '',
        isDisallowedInRobotsTxt: '',
        isIndexableDueToMetaRobots: '',
        isIndexableDueToXRobotsTag: '',
        lighthousePerformance: '',
        lighthouseFCP: '',
        lighthouseTTI: '',
        lighthouseSI: '',
        lighthouseTBT: '',
        lighthouseLCP: '',
        lighthouseCLS: '',
        redirectTarget: '',
        openGraphDescription: '',
        openGraphImage: '',
        openGraphTitle: '',
        openGraphType: '',
        openGraphUrl: '',
        schemaItems: '',
        schemaTypes: '',
        statusCode: '',
        tagManagers: '',
        twitterCard: '',
        twitterDescription: '',
        twitterImage: '',
        twitterSite: '',
        twitterTitle: '',
        url: 'https://www.conductor.com/special/empty',
        urlDepth: '',
        urlFull: 'https://www.conductor.com/special/empty',
        urlType: '',
        visualAnalyticsServices: '',
    },
    {
        analyticsServices: null,
        canonicalType: 'not_applicable',
        canonicalUrl: 'https://www.conductor.com/about/history',
        domain: 'conductor.com',
        https: false,
        indexable: true,
        inXMLSitemap: true,
        isDisallowedInRobotsTxt: false,
        isIndexableDueToMetaRobots: 'yes',
        isIndexableDueToXRobotsTag: undefined,
        lighthousePerformance: { value: 73, range: 'WebVitalRange.NeedsImprovement' },
        lighthouseFCP: { value: 1700, range: 'WebVitalRange.Good' },
        lighthouseTTI: { value: 3100, range: 'WebVitalRange.Good' },
        lighthouseSI: { value: 2500, range: 'WebVitalRange.Good' },
        lighthouseTBT: { value: 394, range: 'WebVitalRange.Bad' },
        lighthouseLCP: { value: 2300, range: 'WebVitalRange.Good' },
        lighthouseCLS: { value: 0, range: 'WebVitalRange.Good' },
        redirectTarget: 'https://www.conductor.com/about/history',
        openGraphDescription: 'Trace Conductor\'s journey from inception to culinary innovation.',
        openGraphImage: 'https://www.conductor.com/images/history.jpg',
        openGraphTitle: 'Conductor - History',
        openGraphType: 'website',
        openGraphUrl: 'https://www.conductor.com/about/history',
        schemaItems: 3,
        schemaTypes: 'BreadcrumbList, Article, Review',
        statusCode: '',
        tagManagers: null,
        twitterCard: 'summary_large_image',
        twitterDescription: 'Trace Conductor\'s journey from inception to culinary innovation.',
        twitterImage: 'https://www.conductor.com/images/history.jpg',
        twitterSite: '@conductor',
        twitterTitle: 'Conductor - History',
        url: 'https://www.conductor.com/about?hello&somethingelse=hello',
        urlDepth: 8,
        urlFull: 'https://www.conductor.com/about?hello&somethingelse=hello',
        urlType: 'PageType.Unreachable',
        visualAnalyticsServices: null,
    },
    {
        analyticsServices: null,
        canonicalType: 'internal_self',
        canonicalUrl: 'https://www.conductor.com/blog',
        domain: undefined,
        https: true,
        indexable: true,
        inXMLSitemap: false,
        isDisallowedInRobotsTxt: false,
        isIndexableDueToMetaRobots: undefined,
        isIndexableDueToXRobotsTag: 'yes',
        lighthousePerformance: { value: 56, range: 'WebVitalRange.Bad' },
        lighthouseFCP: { value: 1000, range: 'WebVitalRange.Good' },
        lighthouseTTI: { value: 8800, range: 'WebVitalRange.Bad' },
        lighthouseSI: { value: 3800, range: 'WebVitalRange.Good' },
        lighthouseTBT: { value: 542, range: 'WebVitalRange.Bad' },
        lighthouseLCP: { value: 2400, range: 'WebVitalRange.Good' },
        lighthouseCLS: { value: 0, range: 'WebVitalRange.Good' },
        redirectTarget: 'https://www.conductor.com/blog',
        openGraphDescription: 'Get culinary insights and recipe recommendations from Conductor\'s blog.',
        openGraphImage: 'https://www.conductor.com/images/blog.jpg',
        openGraphTitle: 'Conductor - Blog',
        openGraphType: 'website',
        openGraphUrl: 'https://www.conductor.com/blog',
        schemaItems: 1,
        schemaTypes: 'LocalBusiness',
        statusCode: 404,
        tagManagers: null,
        twitterCard: 'summary_large_image',
        twitterDescription: 'Get culinary insights and recipe recommendations from Conductor\'s blog.',
        twitterImage: 'https://www.conductor.com/images/blog.jpg',
        twitterSite: '@conductor',
        twitterTitle: 'Conductor - Blog',
        url: undefined,
        urlDepth: 13,
        urlFull: undefined,
        urlType: 'PageType.Redirect',
        visualAnalyticsServices: null,
    },
    {
        analyticsServices: undefined,
        canonicalType: undefined,
        canonicalUrl: undefined,
        domain: undefined,
        https: undefined,
        indexable: undefined,
        inXMLSitemap: undefined,
        isDisallowedInRobotsTxt: undefined,
        isIndexableDueToMetaRobots: undefined,
        isIndexableDueToXRobotsTag: undefined,
        lighthousePerformance: undefined,
        lighthouseFCP: undefined,
        lighthouseTTI: undefined,
        lighthouseSI: undefined,
        lighthouseTBT: undefined,
        lighthouseLCP: undefined,
        lighthouseCLS: undefined,
        redirectTarget: undefined,
        openGraphDescription: undefined,
        openGraphImage: undefined,
        openGraphTitle: undefined,
        openGraphType: undefined,
        openGraphUrl: undefined,
        schemaItems: undefined,
        schemaTypes: undefined,
        statusCode: undefined,
        tagManagers: undefined,
        twitterCard: undefined,
        twitterDescription: undefined,
        twitterImage: undefined,
        twitterSite: undefined,
        twitterTitle: undefined,
        url: 'https://www.conductor.com/special/undefined',
        urlDepth: undefined,
        urlFull: 'https://www.conductor.com/special/undefined',
        urlType: undefined,
        visualAnalyticsServices: undefined,
    },
    {
        analyticsServices: [],
        canonicalType: 'none',
        canonicalUrl: 'https://www.conductor.com/blog/how-long-to-cook-steak',
        domain: 'www.conductor.com',
        https: true,
        indexable: false,
        inXMLSitemap: true,
        isDisallowedInRobotsTxt: undefined,
        isIndexableDueToMetaRobots: 'yes',
        isIndexableDueToXRobotsTag: 'yes',
        lighthousePerformance: { value: 79, range: 'WebVitalRange.NeedsImprovement' },
        lighthouseFCP: { value: 1800, range: 'WebVitalRange.NeedsImprovement' },
        lighthouseTTI: { value: 9000, range: 'WebVitalRange.Bad' },
        lighthouseSI: { value: 2200, range: 'WebVitalRange.Good' },
        lighthouseTBT: { value: 634, range: 'WebVitalRange.Bad' },
        lighthouseLCP: { value: 1100, range: 'WebVitalRange.Good' },
        lighthouseCLS: { value: 0, range: 'WebVitalRange.Good' },
        redirectTarget: 'https://www.conductor.com/blog/how-long-to-cook-steak',
        openGraphDescription: 'Master steak perfection with Conductor\'s expert cooking tips.',
        openGraphImage: 'https://www.conductor.com/images/steak.jpg',
        openGraphTitle: 'Conductor - How long to cook steak',
        openGraphType: 'website',
        openGraphUrl: 'https://www.conductor.com/blog/how-long-to-cook-steak',
        schemaItems: 3,
        schemaTypes: 'Person, Event, LocalBusiness',
        statusCode: null,
        tagManagers: [],
        twitterCard: 'summary_large_image',
        twitterDescription: 'Master steak perfection with Conductor\'s expert cooking tips.',
        twitterImage: 'https://www.conductor.com/images/steak.jpg',
        twitterSite: '@conductor',
        twitterTitle: 'Conductor - How long to cook steak',
        url: 'https://www.conductor.com/blog/how-long-to-cook-steak',
        urlDepth: 0,
        urlFull: 'https://www.conductor.com/blog/how-long-to-cook-steak',
        urlType: 'PageType.Page',
        visualAnalyticsServices: [],
    },
    {
        analyticsServices: null,
        canonicalType: 'invalid',
        canonicalUrl: 'https://www.conductor.com/recipes/easy-filet',
        domain: 'conductor.com',
        https: true,
        indexable: false,
        inXMLSitemap: false,
        isDisallowedInRobotsTxt: false,
        isIndexableDueToMetaRobots: 'no',
        isIndexableDueToXRobotsTag: 'yes',
        lighthousePerformance: { value: 97, range: 'WebVitalRange.Good' },
        lighthouseFCP: { value: 1600, range: 'WebVitalRange.Good' },
        lighthouseTTI: { value: 5000, range: 'WebVitalRange.NeedsImprovement' },
        lighthouseSI: { value: 3600, range: 'WebVitalRange.Good' },
        lighthouseTBT: { value: 252, range: 'WebVitalRange.NeedsImprovement' },
        lighthouseLCP: { value: 1800, range: 'WebVitalRange.Good' },
        lighthouseCLS: { value: 0, range: 'WebVitalRange.Good' },
        redirectTarget: undefined,
        openGraphDescription: 'Enjoy delicious, hassle-free filet recipes with Conductor.',
        openGraphImage: 'https://www.conductor.com/images/filet.jpg',
        openGraphTitle: 'Conductor - Easy filet',
        openGraphType: 'website',
        openGraphUrl: 'https://www.conductor.com/recipes/easy-filet',
        schemaItems: 2,
        schemaTypes: 'Article, Review',
        tagManagers: null,
        statusCode: undefined,
        twitterCard: 'summary_large_image',
        twitterDescription: 'Enjoy delicious, hassle-free filet recipes with Conductor.',
        twitterImage: 'https://www.conductor.com/images/filet.jpg',
        twitterSite: '@conductor',
        twitterTitle: 'Conductor - Easy filet',
        url: 'https://www.conductor.com/recipes/easy-filet',
        urlDepth: 11,
        urlFull: 'https://www.conductor.com/recipes/easy-filet',
        urlType: 'PageType.OverQuota',
        visualAnalyticsServices: null,
    },
    {
        analyticsServices: ['ChangeType.ADOBE_ANALYTICS', 'ChangeType.GOOGLE_ANALYTICS'],
        canonicalType: 'cross_domain',
        canonicalUrl: 'https://www.conductor.com/recipes/vegan-salmon',
        domain: 'www.conductor.com',
        https: undefined,
        indexable: true,
        inXMLSitemap: true,
        isDisallowedInRobotsTxt: true,
        isIndexableDueToMetaRobots: 'not_applicable',
        isIndexableDueToXRobotsTag: 'not_applicable',
        lighthousePerformance: { value: 85, range: 'WebVitalRange.Good' },
        lighthouseFCP: { value: 1200, range: 'WebVitalRange.Good' },
        lighthouseTTI: { value: 8400, range: 'WebVitalRange.Bad' },
        lighthouseSI: { value: 3000, range: 'WebVitalRange.Good' },
        lighthouseTBT: { value: 466, range: 'WebVitalRange.Bad' },
        lighthouseLCP: { value: 1000, range: 'WebVitalRange.Good' },
        lighthouseCLS: { value: 0, range: 'WebVitalRange.Good' },
        redirectTarget: 'https://www.conductor.com/',
        openGraphDescription: 'Dive into plant-based delights with Conductor\'s vegan salmon recipes.',
        openGraphImage: 'https://www.conductor.com/images/salmon.jpg',
        openGraphTitle: 'Conductor - Vegan salmon',
        openGraphType: 'website',
        openGraphUrl: 'https://www.conductor.com/recipes/vegan-salmon',
        schemaItems: 1,
        schemaTypes: 'Product',
        statusCode: 500,
        tagManagers: ['ChangeType.GOOGLE_TAG_MANAGER'],
        twitterCard: 'summary_large_image',
        twitterDescription: 'Dive into plant-based delights with Conductor\'s vegan salmon recipes.',
        twitterImage: 'https://www.conductor.com/images/salmon.jpg',
        twitterSite: '@conductor',
        twitterTitle: 'Conductor - Vegan salmon',
        url: 'https://www.conductor.com/about/history',
        urlDepth: 4,
        urlFull: 'https://www.conductor.com/about/history',
        urlType: 'PageType.Page',
        visualAnalyticsServices: ['ChangeType.MICROSOFT_CLARITY'],
    },
    {
        analyticsServices: null,
        canonicalType: 'internal_self',
        canonicalUrl: 'https://www.conductor.com/blog/5-best-chicken-recipes',
        domain: 'www.conductor.com',
        https: true,
        indexable: true,
        inXMLSitemap: true,
        isDisallowedInRobotsTxt: false,
        isIndexableDueToMetaRobots: 'not_applicable',
        isIndexableDueToXRobotsTag: 'yes',
        lighthousePerformance: { value: 94, range: 'WebVitalRange.Good' },
        lighthouseFCP: { value: 1300, range: 'WebVitalRange.Good' },
        lighthouseTTI: { value: 2100, range: 'WebVitalRange.Good' },
        lighthouseSI: { value: 3000, range: 'WebVitalRange.Good' },
        lighthouseTBT: { value: 515, range: 'WebVitalRange.Bad' },
        lighthouseLCP: { value: 2600, range: 'WebVitalRange.NeedsImprovement' },
        lighthouseCLS: { value: 0, range: 'WebVitalRange.Good' },
        redirectTarget: 'https://www.conductor.com/blog/5-best-chicken-recipes',
        openGraphDescription: 'Discover Conductor\'s top-rated chicken dishes for culinary bliss.',
        openGraphImage: 'https://www.conductor.com/images/chicken.jpg',
        openGraphTitle: 'Conductor - 5 best chicken Recipes',
        openGraphType: 'website',
        openGraphUrl: 'https://www.conductor.com/blog/5-best-chicken-recipes',
        schemaItems: 0,
        schemaTypes: null,
        statusCode: 200,
        tagManagers: null,
        twitterCard: 'summary_large_image',
        twitterDescription: 'Discover Conductor\'s top-rated chicken dishes for culinary bliss.',
        twitterImage: 'https://www.conductor.com/images/chicken.jpg',
        twitterSite: '@conductor',
        twitterTitle: 'Conductor - 5 best chicken Recipes',
        url: 'https://www.conductor.com/blog/5-best-chicken-recipes',
        urlDepth: null,
        urlFull: 'https://www.conductor.com/blog/5-best-chicken-recipes',
        urlType: 'PageType.Missing',
        visualAnalyticsServices: null,
    },
    {
        analyticsServices: ['ChangeType.GOOGLE_ANALYTICS'],
        canonicalType: 'internal_other',
        canonicalUrl: 'https://www.conductor.com/blog/10-best-vegan-recipes',
        domain: 'www.conductor.com',
        https: true,
        indexable: true,
        inXMLSitemap: true,
        isDisallowedInRobotsTxt: false,
        isIndexableDueToMetaRobots: 'yes',
        isIndexableDueToXRobotsTag: 'no',
        lighthousePerformance: { value: 78, range: 'WebVitalRange.NeedsImprovement' },
        lighthouseFCP: { value: 1100, range: 'WebVitalRange.Good' },
        lighthouseTTI: { value: 8200, range: 'WebVitalRange.Bad' },
        lighthouseSI: { value: 3600, range: 'WebVitalRange.Good' },
        lighthouseTBT: { value: 300, range: 'WebVitalRange.NeedsImprovement' },
        lighthouseLCP: { value: 1400, range: 'WebVitalRange.Good' },
        lighthouseCLS: { value: 0, range: 'WebVitalRange.Good' },
        redirectTarget: 'https://www.conductor.com/blog/10-best-vegan-recipes',
        openGraphDescription: 'Explore Conductor\'s finest vegan creations for a plant-powered feast.',
        openGraphImage: 'https://www.conductor.com/images/vegan.jpg',
        openGraphTitle: 'Conductor - 10 best vegan Recipes',
        openGraphType: 'website',
        openGraphUrl: 'https://www.conductor.com/blog/10-best-vegan-recipes',
        schemaItems: 3,
        schemaTypes: 'BreadcrumbList, Organization, Review',
        statusCode: 404,
        tagManagers: ['ChangeType.GOOGLE_TAG_MANAGER'],
        twitterCard: 'summary_large_image',
        twitterDescription: 'Explore Conductor\'s finest vegan creations for a plant-powered feast.',
        twitterImage: 'https://www.conductor.com/images/vegan.jpg',
        twitterSite: '@conductor',
        twitterTitle: 'Conductor - 10 best vegan Recipes',
        url: 'https://www.conductor.com/blog/10-best-vegan-recipes',
        urlDepth: undefined,
        urlFull: 'https://www.conductor.com/blog/10-best-vegan-recipes',
        urlType: 'PageType.Page',
        visualAnalyticsServices: ['ChangeType.SMARTLOOK'],
    },
];

const data = {
    'https://www.conductor.com/': {
      titleTag: "Conductor - Your Partner in SEO Success",
      description: "Conductor is your partner in SEO success. Our platform empowers marketers to unlock the full potential of their website's organic visibility.",
      h1: "SEO Success with Conductor"
    },
    'https://www.conductor.com/recipes': {
      titleTag: "Conductor - Delicious Recipes for Every Occasion",
      description: "Discover delicious recipes for every occasion with Conductor. From easy filet to vegan salmon, find inspiration for your next meal.",
      h1: "Delicious Recipes for Every Occasion"
    },
    'https://www.conductor.com/blog': {
      titleTag: "Conductor - SEO Blog for Marketers",
      description: "Explore the latest trends, tips, and strategies in SEO with Conductor's blog. Stay updated on the ever-evolving world of search engine optimization.",
      h1: "SEO Blog for Marketers"
    },
    'https://www.conductor.com/about': {
      titleTag: "Conductor - About Us",
      description: "Learn more about Conductor and our commitment to empowering marketers with SEO solutions. Discover our mission, team, and values.",
      h1: "About Us"
    },
    'https://www.conductor.com/about/history': {
      titleTag: "Conductor - Our History",
      description: "Explore the history of Conductor, from our founding to our evolution as a leading SEO platform. Learn about our journey and milestones.",
      h1: "Our History"
    },
    'https://www.conductor.com/blog/how-long-to-cook-steak': {
      titleTag: "Conductor - How Long to Cook Steak",
      description: "Discover the perfect cooking times for steak with Conductor's guide. Learn how to achieve your desired level of doneness with expert tips.",
      h1: "How Long to Cook Steak"
    },
    'https://www.conductor.com/recipes/easy-filet': {
      titleTag: "Conductor - Easy Filet Recipe",
      description: "Try Conductor's easy filet recipe for a delicious and satisfying meal. Learn how to cook filet to perfection with our step-by-step guide.",
      h1: "Easy Filet Recipe"
    },
    'https://www.conductor.com/recipes/vegan-salmon': {
      titleTag: "Conductor - Vegan Salmon Recipe",
      description: "Enjoy a plant-based twist on classic salmon with Conductor's vegan salmon recipe. Discover a flavorful and nutritious alternative to seafood.",
      h1: "Vegan Salmon Recipe"
    },
    'https://www.conductor.com/blog/5-best-chicken-recipes': {
      titleTag: "Conductor - 5 Best Chicken Recipes",
      description: "Explore Conductor's curated list of the 5 best chicken recipes for delicious and satisfying meals. Elevate your cooking with these tasty dishes.",
      h1: "5 Best Chicken Recipes"
    },
    'https://www.conductor.com/blog/10-best-vegan-recipes': {
      titleTag: "Conductor - 10 Best Vegan Recipes",
      description: "Discover Conductor's selection of the 10 best vegan recipes for plant-based cooking inspiration. Explore flavorful and nutritious dishes.",
      h1: "10 Best Vegan Recipes"
    }
  };

const updatedMockData = mockGridData.map((row) => {
    return {
        analyticsServices: row.analyticsServices,
        canonicalType: row.canonicalType,
        canonicalUrl: row.canonicalUrl,
        domain: row.domain,
        https: row.https,
        indexable: row.indexable,
        inXMLSitemap: row.inXMLSitemap,
        isDisallowedInRobotsTxt: row.isDisallowedInRobotsTxt,
        isIndexableDueToMetaRobots: row.isIndexableDueToMetaRobots,
        isIndexableDueToXRobotsTag: row.isIndexableDueToXRobotsTag,
        h1: data[row.url]?.h1 || row.canonicalUrl,
        lighthousePerformance: row.lighthousePerformance,
        lighthouseFCP: row.lighthouseFCP,
        lighthouseTTI: row.lighthouseTTI,
        lighthouseSI: row.lighthouseSI,
        lighthouseTBT: row.lighthouseTBT,
        lighthouseLCP: row.lighthouseLCP,
        lighthouseCLS: row.lighthouseCLS,
        metaDescription: data[row.url]?.description || row.canonicalUrl,
        redirectTarget: row.redirectTarget,
        openGraphDescription: row.openGraphDescription,
        openGraphImage: row.openGraphImage,
        openGraphTitle: row.openGraphTitle,
        openGraphType: row.openGraphType,
        openGraphUrl: row.openGraphUrl,
        schemaItems: row.schemaItems,
        schemaTypes: row.schemaTypes,
        statusCode: row.statusCode,
        tagManagers: row.tagManagers,
        title: data[row.url]?.titleTag || row.canonicalUrl,
        twitterCard: row.twitterCard,
        twitterDescription: row.twitterDescription,
        twitterImage: row.twitterImage,
        twitterSite: row.twitterSite,
        twitterTitle: row.twitterTitle,
        url: row.url,
        urlDepth: row.urlDepth,
        urlFull: row.urlFull,
        urlType: row.urlType,
        visualAnalyticsServices: row.visualAnalyticsServices,
    }
})

console.log(updatedMockData)
